name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Upgrade pip and install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Clean PyInstaller outputs
        shell: pwsh
        run: |
          if (Test-Path .\dist) { Remove-Item -Recurse -Force .\dist }
          if (Test-Path .\build) { Remove-Item -Recurse -Force .\build }
          if (Test-Path .\UIBridge.spec) { Remove-Item -Force .\UIBridge.spec }
          if (Test-Path .\ui.spec) { Remove-Item -Force .\ui.spec }
          if (Test-Path .\UIBridgeLauncher.spec) { Remove-Item -Force .\UIBridgeLauncher.spec }

      - name: Build agent EXE (UIBridge.exe)
        run: >
          pyinstaller --noconfirm --clean --noconsole
          --name UIBridge
          --version-file installer/version_info.txt
          --hidden-import aiosqlite
          --hidden-import sqlalchemy.dialects.sqlite.aiosqlite
          --collect-submodules sqlalchemy.dialects
          app/main.py

      - name: Build CLI EXE (ui.exe)
        run: >
          pyinstaller --noconfirm --clean
          --name ui
          --version-file installer/version_info.txt
          --hidden-import aiosqlite
          --hidden-import sqlalchemy.dialects.sqlite.aiosqlite
          --collect-submodules sqlalchemy.dialects
          app/cli/entry.py

      - name: Build Launcher EXE (UIBridgeLauncher.exe)
        run: >
          pyinstaller --noconfirm --clean --noconsole
          --name UIBridgeLauncher
          --version-file installer/version_info.txt
          app/launcher_gui.py

      - name: Prepare Windows package folder (single ZIP)
        shell: pwsh
        run: |
          $pkg = "UIBridge-Windows"
          if (Test-Path $pkg) { Remove-Item -Recurse -Force $pkg }
          New-Item -ItemType Directory -Force $pkg | Out-Null

          # Copy runtime folders
          Copy-Item -Recurse -Force "dist\UIBridge" "$pkg\UIBridge"
          Copy-Item -Recurse -Force "dist\ui" "$pkg\ui"
          Copy-Item -Recurse -Force "dist\UIBridgeLauncher" "$pkg\UIBridgeLauncher"

          # Write helper .cmd files as arrays of lines (robust in YAML + PowerShell)
          $startAgent = @(
            '@echo off',
            'setlocal',
            'cd /d "%~dp0"',
            'set "AGENT=%CD%\UIBridge\UIBridge.exe"',
            'if not exist "%AGENT%" (',
            '  echo Agent not found: "%AGENT%"',
            '  pause',
            '  exit /b 1',
            ')',
            'start "" "%AGENT%"',
            'timeout /t 3 >nul',
            'powershell -NoProfile -Command "try { (Invoke-WebRequest -UseBasicParsing ''http://127.0.0.1:5025/health'').StatusCode -eq 200 } catch { $false }" | findstr /i True >nul',
            'if errorlevel 1 (',
            '  echo If this is the first run, a Windows Firewall prompt may be waiting behind other windows. Allow access (Private), then try again.',
            '  pause',
            ')',
            'endlocal'
          )
          $startAgent | Set-Content -Path "$pkg\Start UIBridge Agent.cmd" -Encoding UTF8

          $openCli = @(
            '@echo off',
            'setlocal',
            'cd /d "%~dp0ui"',
            'start "" cmd /k ui.exe --help',
            'endlocal'
          )
          $openCli | Set-Content -Path "$pkg\Open UIBridge CLI.cmd" -Encoding UTF8

          # Copy installer helper scripts
          Copy-Item -Force "scripts\install_agent_startup.ps1" "$pkg\install_agent_startup.ps1"
          Copy-Item -Force "scripts\uninstall_agent_startup.ps1" "$pkg\uninstall_agent_startup.ps1"
          Copy-Item -Force "scripts\install_cli_shim.ps1" "$pkg\install_cli_shim.ps1"

          # README as array of lines; save UTF-8 to preserve punctuation
          $readme = @(
            'UIBridge CLI — Windows Bundle',
            '',
            'Files:',
            '- UIBridge\UIBridge.exe       (local agent)',
            '- ui\ui.exe                   (command-line tool)',
            '- UIBridgeLauncher\UIBridgeLauncher.exe (friendly launcher UI)',
            '',
            'Quick start:',
            '1) Double-click UIBridgeLauncher.exe',
            '   - Click "Start Agent" to start the local agent.',
            '   - Click "Open CLI" to open a terminal with ui.exe.',
            '2) In the terminal, try:',
            '   ui doctor',
            '   ui open example.com',
            '   ui search drake',
            '',
            'Spotify (first time):',
            '1) Run: ui setup',
            '   - Paste your Spotify "Client ID" (public; no secret).',
            '   - A browser opens; complete login.',
            '2) Then try:',
            '   ui play "moment apart odesza"',
            '   ui now',
            '   ui pause',
            '',
            'Notes:',
            '- If the CLI says it cannot connect, start the agent first (UIBridge.exe or via the launcher).',
            '- If browser commands fail, click "Start Agent" in the launcher and try again.',
            '- Windows may warn about downloaded ZIPs. Right-click the ZIP > Properties > Unblock, then extract.',
            '',
            'Support: see the project README on GitHub.'
          )
          $readme | Set-Content -Path "$pkg\README.txt" -Encoding UTF8

      - name: Archive Windows package
        shell: pwsh
        run: |
          if (Test-Path "UIBridge-Windows.zip") { Remove-Item -Force "UIBridge-Windows.zip" }
          Compress-Archive -Path "UIBridge-Windows\*" -DestinationPath "UIBridge-Windows.zip" -Force

      - name: Upload artifact for publish job
        uses: actions/upload-artifact@v4
        with:
          name: UIBridge-zip
          path: UIBridge-Windows.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: UIBridge-zip
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: UIBridge-Windows.zip
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
