name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

# allow creating releases
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --noconsole --name UIBridge app/main.py

      - name: Archive EXE
        run: |
          powershell Compress-Archive -Path "dist\\UIBridge\\UIBridge.exe" -DestinationPath "UIBridge-Windows.zip"

      - name: Upload artifacts for this run
        uses: actions/upload-artifact@v4
        with:
          name: UIBridge-zip
          path: UIBridge-Windows.zip

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: UIBridge-zip
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: UIBridge-Windows.zip
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
